version: '3.9'

services:
  influxdb:
    image: library/influxdb:1.8
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_ADMIN_PASSWORD: admin
      INFLUXDB_DB: sample_database
      INFLUXDB_HTTP_AUTH_ENABLED: true
    volumes:
      - ./container/influx/data:/var/lib/influxdb2
    # - container/influx/config/config.yml:/etc/influxdb2/config.yml