server:
  port: 8080
kafka:
  server: ${KAFKA_BOOTSTRAP_SERVER:localhost:9092}
influx:
  url: ${INFLUXDB_URL:http://localhost:8086}
  username: ${INFLUXDB_USERNAME:sampleuser}
  password: ${INFLUX_DB_PASSWORD:samplepassword}
  token: ${INFLUX_DB_TOKEN:ZSvLnfSw_0f8i7E1e2L3Oc9_UdStXXgRt7grciWHwPGcx-DCMThDXv6FK1QaRIZ-aCEf4CEt4pgQ4WDuM1AtCA==}
  org: sample
  bucket: sample
