server:
  port: 8080
kafka:
  server: ${KAFKA_BOOTSTRAP_SERVER:localhost:9092}
spring:
  influxdb:
    url: ${INFLUX_DB_URL:http://localhost:8086}
    username: ktj7916
    password: asd159753!
    database: sample_database
    retention-policy: autogen